---
name: Rust

"on":
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      any_changed: ${{ steps.detect-changes.outputs.any_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: detect-changes
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.rs
            **/*.toml
            **/Cargo.lock

      - name: Print changed files
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file"
          done

  lint:
    name: Lint code
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    container:
      image: ghcr.io/jdno/rust:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout Otterdone repository
        uses: actions/checkout@v4
        with:
          repository: otterdone/otterdone

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.7.0

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  style:
    name: Check style
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    container:
      image: ghcr.io/jdno/rust:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Rustfmt
        run: cargo fmt --all -- --check

  test:
    name: Run tests
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    container:
      image: ghcr.io/jdno/rust:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout Otterdone repository
        uses: actions/checkout@v4
        with:
          repository: otterdone/otterdone

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.7.0

      - name: Run tests
        run: cargo test
